name: Feature CICD Development

on:
  push:
    branches:
      - 'feature**' f

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Test
        run: echo "Deploying onto the feature branch"
